import {Metadata} from "next";

import MainNav from "./_components/main-nav";
import "./globals.css";

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className="min-h-screen bg-white text-slate-900 antialiased">
        <MainNav/>
        <main className="mx-auto max-w-5xl px-5 py-8">
            {children}
        </main>
        <footer className="mx-auto max-w-5xl px-5 py-6 text-sm text-slate-500">Root layout footer</footer>
        </body>
        </html>
    )
}
